### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by zachvlat** [pixincreate/mGMSCompat#2]
I have a secondary phone (Xiaomi MI5) to test this out, if you want.

**Comment by pixincreate** [comment]
No. This tiny little project is still in its infancy and is just getting started. It'll take a lot of time for me to implement since I'm a beginner in Magisk and Android development.  

Thank you showing interest in this project. I'll when the module becomes reaches a stage where testing can be done.

**Comment by lepras** [comment]
> Thank you showing interest in this project. I'll when the module becomes reaches a stage where testing can be done.

Is there any new development?

**Comment by pixincreate** [comment]
No, not yet. I cannot leverage my daily driver for testing the module and yes, this project is always in my head and I hope to work on this real soon.
